#!/usr/bin/env node
// Batch 11 generator — the externally-provided "g3" set (40 PS, 50 CR, 10 DS),
// CHECKED and CORRECTED before import. No RC/GI/TA/TP, no groups this batch.
//
// Corrections applied to the raw source (see scripts/check-batch11.mjs for the
// independent re-derivation that enforces them):
//   PS relabeled (right value, wrong key): 13,22,23,27,28,33,35,37,38,39
//   PS broken choice sets repaired:        06 (all were ÷11), 14, 17, 31, 40
//   PS multiple-correct tightened:         26, 36
//   DS-93 stem made consistent (answer C); CR-66 stem made logically valid (B)
//   LaTeX normalized (\frac not \rac; proper escaping throughout).
//
// LaTeX uses single backslashes in these JS string literals; JSON.stringify
// re-escapes them to the double backslashes the bank expects.
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const ABC = (arr) => arr.map((text, i) => ({ key: "ABCDE"[i], text: String(text) }));

function ps(id, [topic, difficulty, stem, ch, ans, explanation, t = 120]) {
  return {
    id, section: "quant", type: "problem_solving", topic, difficulty, orderIndex: 0,
    stem, assets: {}, choices: ABC(ch), correctAnswer: { format: "single", value: ans },
    explanation, estimatedTimeSeconds: t,
  };
}
function cr(id, [topic, difficulty, passageOrStimulus, stem, ch, ans, explanation, t = 105]) {
  return {
    id, section: "verbal", type: "critical_reasoning", topic, difficulty, orderIndex: 0,
    passageOrStimulus, stem, assets: {}, choices: ABC(ch),
    correctAnswer: { format: "single", value: ans }, explanation, estimatedTimeSeconds: t,
  };
}
function ds(id, [topic, difficulty, stem, ans, explanation, t = 120]) {
  return {
    id, section: "data_insights", type: "data_sufficiency", topic, difficulty, orderIndex: 0,
    stem, assets: {}, correctAnswer: { format: "single", value: ans },
    explanation, estimatedTimeSeconds: t,
  };
}

// ── Problem Solving (40) — g3-quant-01..40 ────────────────────────────────────
const PS = [
  ["arithmetic", "easy", "What is the value of $24-3(5)+8$?", ["23", "17", "11", "31", "29"], "B", "Multiply first: $3(5)=15$. Then $24-15+8=17$.", 90],
  ["percents", "easy", "What is $12\\%$ of $350$?", ["45", "42", "36", "40", "32"], "B", "$0.12\\times 350 = 42$.", 90],
  ["fractions", "easy", "What is $\\frac{5}{8}-\\frac{1}{4}$?", ["$\\frac{1}{2}$", "$\\frac{7}{8}$", "$\\frac{1}{8}$", "$\\frac{5}{12}$", "$\\frac{3}{8}$"], "E", "Rewrite $\\frac{1}{4}=\\frac{2}{8}$. Then $\\frac{5}{8}-\\frac{2}{8}=\\frac{3}{8}$.", 90],
  ["ratios", "easy", "Two numbers are in the ratio $4:7$ and their sum is $33$. What is the smaller number?", ["16", "11", "14", "18", "12"], "E", "The ratio has $4+7=11$ parts, each $33/11=3$. The smaller number is $4\\times 3=12$.", 100],
  ["averages", "easy", "The average of $4$ numbers is $18$. If three of the numbers sum to $47$, what is the fourth number?", ["27", "25", "21", "19", "23"], "B", "The total is $4\\times 18=72$, so the fourth number is $72-47=25$.", 100],
  ["number_properties", "easy", "Which of the following is divisible by $11$?", ["570", "583", "600", "615", "620"], "B", "For $583$, the alternating digit sum is $(5+3)-8=0$, so $583=11\\times 53$ is divisible by $11$. None of $570$, $600$, $615$, or $620$ is a multiple of $11$.", 100],
  ["algebra", "easy", "If $7x-5=30$, what is the value of $x$?", ["6", "5", "4", "7", "3"], "B", "Add $5$ to both sides: $7x=35$, so $x=5$.", 90],
  ["geometry", "easy", "A triangular pennant has two equal sides of $13$ inches each and a base of $10$ inches. What is its perimeter, in inches?", ["34", "36", "38", "40", "42"], "B", "Perimeter $=13+13+10=36$.", 90],
  ["coordinate_geometry", "easy", "What is the midpoint of the segment joining $(-2,4)$ and $(6,-2)$?", ["(2, 1)", "(3, 1)", "(2, 0)", "(1, 1)", "(2, 2)"], "A", "Midpoint $=\\left(\\frac{-2+6}{2},\\frac{4+(-2)}{2}\\right)=(2,1)$.", 100],
  ["rates", "easy", "A train travels $180$ miles in $4.5$ hours at a constant rate. What is its speed, in miles per hour?", ["36", "50", "42", "40", "45"], "D", "Speed $=180/4.5=40$.", 100],
  ["work", "medium", "Machine A can finish a job in $10$ hours and machine B can finish the same job in $15$ hours. How long would they take working together?", ["$12$ hours", "$6$ hours", "$5$ hours", "$7.5$ hours", "$8$ hours"], "B", "Their rates add: $\\frac{1}{10}+\\frac{1}{15}=\\frac{1}{6}$, so together they take $6$ hours.", 150],
  ["mixtures", "hard", "How many liters of pure acid should be added to $8$ liters of a $25\\%$ acid solution to make a $40\\%$ solution?", ["4", "1", "2", "5", "3"], "C", "The solution has $0.25\\times 8=2$ liters of acid. Adding $x$ liters of acid: $\\frac{2+x}{8+x}=0.40$, so $2+x=3.2+0.4x$, giving $0.6x=1.2$ and $x=2$.", 180],
  ["exponents", "medium", "If $2^{x+1}=128$, what is the value of $x$?", ["5", "6", "7", "4", "3"], "B", "Since $128=2^7$, we have $x+1=7$, so $x=6$.", 120],
  ["inequalities", "hard", "If $|3x-4|>11$, which of the following could be the value of $x$?", ["1", "3", "6", "2", "4"], "C", "$|3x-4|>11$ means $3x-4>11$ or $3x-4<-11$, i.e. $x>5$ or $x<-\\frac{7}{3}$. Of the choices, only $x=6$ satisfies this.", 150],
  ["statistics", "medium", "The median of six numbers is $14$, and the two middle numbers are $13$ and $15$. If the six numbers sum to $84$, what is their average?", ["12", "13", "14", "15", "16"], "C", "The average is the total divided by the count: $84/6=14$.", 120],
  ["probability", "medium", "A bag contains $5$ red marbles, $3$ blue marbles, and $2$ green marbles. If one marble is chosen at random, what is the probability that it is not blue?", ["$\\frac{1}{5}$", "$\\frac{3}{5}$", "$\\frac{7}{10}$", "$\\frac{2}{5}$", "$\\frac{4}{5}$"], "C", "There are $10$ marbles, of which $5+2=7$ are not blue, so the probability is $\\frac{7}{10}$.", 120],
  ["counting", "medium", "How many three-digit positive integers have all distinct digits and end in an even digit?", ["360", "328", "324", "400", "432"], "B", "If the units digit is $0$: $9\\times 8=72$ numbers. If the units digit is $2,4,6,$ or $8$: $4\\times 8\\times 8=256$ numbers. The total is $72+256=328$.", 150],
  ["geometry", "medium", "A circle has radius $9$. What is its area in terms of $\\pi$?", ["$81\\pi$", "$18\\pi$", "$36\\pi$", "$72\\pi$", "$9\\pi$"], "A", "Area $=\\pi r^2=\\pi(9^2)=81\\pi$.", 120],
  ["coordinate_geometry", "medium", "What is the slope of the line through $(2,5)$ and $(8,17)$?", ["2", "3", "4", "1", "6"], "A", "Slope $=\\frac{17-5}{8-2}=\\frac{12}{6}=2$.", 120],
  ["sequences", "medium", "The first term of an arithmetic sequence is $7$ and the common difference is $4$. What is the $10$th term?", ["43", "39", "40", "35", "47"], "A", "Using $a_n=a_1+(n-1)d$: $a_{10}=7+9\\times 4=43$.", 120],
  ["fractions", "hard", "Which is greater, $\\frac{7}{12}$ or $\\frac{3}{5}$?", ["$\\frac{7}{12}$", "They are equal", "$\\frac{3}{5}$", "Cannot be determined", "$\\frac{5}{7}$"], "C", "Cross-multiply: $7\\times 5=35$ and $3\\times 12=36$. Since $36>35$, $\\frac{3}{5}$ is greater.", 150],
  ["ratios", "hard", "A recipe uses flour and water in the ratio $5:2$. If $28$ cups of mixture are made, how many cups are flour?", ["18", "20", "16", "14", "12"], "B", "Total parts $=5+2=7$, each $28/7=4$. Flour $=5\\times 4=20$.", 150],
  ["algebra", "hard", "If $\\frac{2x-3}{5}=\\frac{x+9}{10}$, what is $x$?", ["13", "11", "9", "7", "5"], "E", "Multiply both sides by $10$: $2(2x-3)=x+9$, so $4x-6=x+9$, giving $3x=15$ and $x=5$.", 150],
  ["number_properties", "hard", "What is the remainder when $7^{20}$ is divided by $6$?", ["0", "1", "2", "3", "4"], "B", "$7\\equiv 1 \\pmod 6$, so $7^{20}\\equiv 1^{20}\\equiv 1 \\pmod 6$.", 150],
  ["exponents", "hard", "If $x^2=49$ and $x<0$, what is the value of $x$?", ["7", "-7", "49", "-49", "0"], "B", "$x^2=49$ gives $x=\\pm 7$; the condition $x<0$ gives $x=-7$.", 120],
  ["inequalities", "medium", "If $-2<3x+1\\le 10$, which of the following is a possible value of $x$?", ["-1", "-2", "4", "5", "1"], "E", "Subtract $1$: $-3<3x\\le 9$. Divide by $3$: $-1<x\\le 3$. Of the choices, only $x=1$ lies in this range.", 120],
  ["statistics", "medium", "The average of five numbers is $24$. If four of the numbers sum to $91$, what is the fifth number?", ["27", "19", "29", "25", "17"], "C", "The total is $5\\times 24=120$, so the fifth number is $120-91=29$.", 120],
  ["probability", "medium", "A spinner has $8$ equal sectors numbered $1$ through $8$. What is the probability of landing on a number greater than $5$?", ["$\\frac{1}{2}$", "$\\frac{3}{8}$", "$\\frac{1}{4}$", "$\\frac{5}{8}$", "$\\frac{2}{3}$"], "B", "Numbers greater than $5$ are $6,7,8$: three of eight outcomes, so the probability is $\\frac{3}{8}$.", 120],
  ["counting", "medium", "In how many ways can $4$ books be arranged on a shelf?", ["24", "12", "16", "20", "18"], "A", "The number of arrangements is $4!=24$.", 120],
  ["geometry", "medium", "A rectangle has length $12$ and width $7$. What is its area?", ["72", "84", "96", "56", "64"], "B", "Area $=12\\times 7=84$.", 120],
  ["coordinate_geometry", "medium", "What is the distance between $(3,4)$ and $(9,12)$?", ["8", "10", "6", "9", "7"], "B", "Distance $=\\sqrt{(9-3)^2+(12-4)^2}=\\sqrt{36+64}=\\sqrt{100}=10$.", 120],
  ["sequences", "medium", "The terms of a sequence are $3, 6, 12, 24, \\dots$. What is the next term?", ["30", "48", "36", "42", "54"], "B", "Each term is double the previous one, so the next term is $24\\times 2=48$.", 100],
  ["number_properties", "hard", "How many positive divisors does $180$ have?", ["12", "16", "18", "24", "20"], "C", "$180=2^2\\cdot 3^2\\cdot 5$, so the number of divisors is $(2+1)(2+1)(1+1)=18$.", 150],
  ["geometry", "hard", "A square has a diagonal of length $10\\sqrt{2}$. What is its side length?", ["10", "$5\\sqrt{2}$", "20", "$10\\sqrt{2}$", "5"], "A", "For a square, the diagonal is $s\\sqrt{2}$. So $s\\sqrt{2}=10\\sqrt{2}$, giving $s=10$.", 150],
  ["algebra", "hard", "If $x+y=12$ and $x-y=4$, what is the value of $x^2-y^2$?", ["32", "48", "64", "72", "96"], "B", "$x^2-y^2=(x+y)(x-y)=12\\times 4=48$.", 150],
  ["inequalities", "hard", "If $2x-1<5$ and $x+3\\ge 1$, which of the following is a possible value of $x$?", ["-3", "1", "3", "4", "5"], "B", "The first inequality gives $x<3$; the second gives $x\\ge -2$. So $-2\\le x<3$, and of the choices only $x=1$ is in this range.", 150],
  ["statistics", "hard", "The mean of $6$ integers is $15$. If the largest integer is removed, the mean of the remaining $5$ integers is $14$. What was the largest integer?", ["23", "25", "20", "21", "24"], "C", "The total of the $6$ integers is $6\\times 15=90$; the total of the remaining $5$ is $5\\times 14=70$. The largest is $90-70=20$.", 180],
  ["probability", "hard", "Two fair dice are rolled. What is the probability that the sum is at least $10$?", ["$\\frac{1}{12}$", "$\\frac{1}{9}$", "$\\frac{1}{6}$", "$\\frac{1}{4}$", "$\\frac{5}{18}$"], "C", "Sums of $10,11,$ and $12$ occur in $3+2+1=6$ of $36$ outcomes: $\\frac{6}{36}=\\frac{1}{6}$.", 150],
  ["counting", "hard", "How many distinct arrangements of the letters in $LEVEL$ are possible?", ["60", "24", "12", "30", "20"], "D", "$LEVEL$ has two L's and two E's, so the number of distinct arrangements is $\\frac{5!}{2!\\,2!}=\\frac{120}{4}=30$.", 150],
  ["rates", "hard", "A cyclist rides at $12$ miles per hour for $2$ hours and at $18$ miles per hour for $2$ hours. What is the average speed for the whole trip?", ["15 mph", "14 mph", "16 mph", "13 mph", "17 mph"], "A", "Total distance $=12\\times 2+18\\times 2=24+36=60$ miles in $4$ hours, so the average speed is $60/4=15$ mph.", 180],
];

// ── Critical Reasoning (50) — g3-cr-41..90 ────────────────────────────────────
const CR = [
  ["assumption", "easy", "A bakery increased the price of its most popular loaf by 10 percent and then sold more loaves the next week than the week before. The manager concludes that customers value the bread more after the price increase.", "Which of the following is an assumption on which the manager's conclusion depends?", ["The bakery sold at least as many pastries as loaves.", "No other change affected demand for the loaf during the two weeks.", "The loaf's ingredients are locally sourced.", "The bakery's profit margin decreased.", "The loaf was larger in the second week."], "B", "The manager infers higher valuation from a price increase plus higher sales. That holds only if no other factor explains the increase in sales, which is what choice B states.", 90],
  ["strengthen", "easy", "A city installed reflective lane markers on a curved road and later saw a decline in nighttime crashes on that road. Officials conclude that the markers improved safety.", "Which of the following, if true, most strengthens the officials' conclusion?", ["Traffic volume on the road stayed about the same.", "Nearby roads also had fewer nighttime crashes.", "Some drivers prefer daytime travel.", "The markers were inexpensive to install.", "The road was repaved the year before."], "A", "If traffic volume stayed about the same, the drop in crashes is less likely to be explained by reduced exposure, making the marker explanation more plausible.", 90],
  ["weaken", "easy", "After a company replaced printed manuals with short video tutorials, support calls fell. The company concludes that the videos are easier for customers to use.", "Which of the following, if true, most weakens the company's conclusion?", ["Customer calls fell more sharply on weekends.", "The company also simplified the product interface at the same time.", "Some customers still prefer paper documents.", "The videos are available in two languages.", "The support staff were trained more recently."], "B", "If the interface was simplified at the same time, the drop in support calls may be due to the interface change rather than the videos being easier to use.", 90],
  ["evaluate", "easy", "A school argues that its new tutoring program raised mathematics scores because average scores rose after the program began.", "Which of the following would be most useful to determine whether the school's conclusion is justified?", ["Whether students liked the tutors.", "Whether scores also rose at schools without the program.", "Whether the tutoring rooms were comfortable.", "Whether the program had a logo.", "Whether teachers received parking passes."], "B", "A comparison school helps test whether the increase reflects the tutoring program or a broader trend, directly addressing the causal question.", 90],
  ["flaw", "easy", "A restaurant noticed that diners who ordered dessert spent more overall than diners who did not. The owner concludes that offering free desserts will increase total revenue.", "The owner's reasoning is flawed because it", ["confuses correlation with causation.", "uses too large a sample.", "assumes desserts taste better than entrees.", "ignores all numerical data.", "compares two identical groups."], "A", "Diners who order dessert may already be inclined to spend more. The owner treats an association as proof that desserts cause higher revenue.", 90],
  ["inference", "easy", "The museum is closed on Mondays. On Tuesday, visitors may enter only the west wing because the east wing is being renovated.", "Which of the following can be inferred from the information above?", ["The museum is open to all visitors every Tuesday.", "The east wing is open on Mondays.", "On Tuesday, visitors cannot enter the east wing.", "The museum has no west wing.", "Renovation always occurs on Mondays."], "C", "On Tuesday, visitors may enter only the west wing because the east wing is being renovated, so they cannot enter the east wing.", 90],
  ["paradox", "easy", "A ferry line increased the number of sailings this summer, yet total passenger wait times also increased.", "Which of the following, if true, best resolves the apparent discrepancy?", ["The ferry line added a new marketing campaign.", "More passengers than usual arrived at the docks.", "The ferries were painted a different color.", "The company offered free water onboard.", "Some passengers preferred walking."], "B", "If demand rose even more than the increase in sailings, average wait times could still rise, resolving the contradiction.", 90],
  ["boldface", "easy", "The planning memo says that the new bike lanes will reduce congestion. **City traffic data from the last three years show that congestion has risen most on streets without bike lanes.** **Therefore, the city should install bike lanes first on the busiest corridors.**", "In the argument, the first boldfaced statement plays which role, and the second boldfaced statement plays which role?", ["Evidence; conclusion", "Conclusion; evidence", "Counterevidence; conclusion", "Conclusion; recommendation", "Recommendation; evidence"], "A", "The data statement supports the case for bike lanes, so it is evidence; the final statement is the conclusion the argument draws from it.", 100],
  ["conclusion-main-point", "medium", "A housing agency notes that when landlords receive faster permit approvals, renovation projects finish sooner. It also notes that faster renovations reduce the number of vacant units. The agency concludes that speeding permit approvals can help stabilize neighborhood rents.", "Which of the following most accurately states the main point of the argument?", ["Permit approvals should never be delayed.", "Faster approvals can help stabilize neighborhood rents.", "Vacant units are always undesirable.", "Renovation projects should be eliminated.", "Landlords prefer higher rents."], "B", "The chain of support leads to the broader claim that faster permit approvals can help stabilize rents, which is the main conclusion.", 100],
  ["plan_strategy", "medium", "A city wants to increase recycling without raising taxes. Officials are choosing between several outreach plans.", "Which of the following plans is most likely to achieve the city's goal?", ["Offer free collection bins and reduce pickup frequency.", "Launch a citywide campaign using existing staff and digital notices.", "Hire an outside consultant and build a new facility.", "Raise fines dramatically for households that do not recycle.", "Cut all recycling services for one month."], "B", "A campaign using existing staff and digital notices plausibly improves recycling while avoiding major added cost, fitting the no-new-tax goal.", 100],
  ["assumption", "medium", "A fitness app reports that users who complete its evening stretching routine sleep longer on average. The company concludes that the routine improves sleep duration.", "Which of the following is an assumption required by the company's conclusion?", ["The users who stretch are more athletic than other users.", "The stretching routine does not itself keep users awake later.", "All users own smartphones.", "Users prefer stretching to running.", "The app charges a subscription fee."], "B", "The conclusion requires that the routine not have a countervailing effect such as keeping users awake; otherwise the longer sleep could not be attributed to it.", 100],
  ["strengthen", "medium", "A theater says that moving its shows from Saturday night to Thursday night will increase attendance because Thursday has fewer competing events.", "Which of the following, if true, most strengthens the theater's reasoning?", ["Thursday tickets are slightly cheaper.", "Many of the theater's regular patrons are unavailable on Thursdays.", "Other entertainment options are in fact limited on Thursdays.", "The theater has a larger lobby on Saturdays.", "The cast prefers Saturday rehearsals."], "C", "If other entertainment options are genuinely limited on Thursdays, the claimed advantage is real and the move is more likely to raise attendance.", 100],
  ["weaken", "medium", "A hospital claims that its new appointment reminder texts reduced no-show rates because fewer patients missed appointments after the texts began.", "Which of the following, if true, most weakens the hospital's claim?", ["The texts were sent only to new patients.", "The hospital also started offering free parking at the same time.", "Some patients replied to the texts.", "The reminders were sent at 8 a.m.", "The hospital uses the same software for billing."], "B", "If free parking was introduced at the same time, the lower no-show rate could be due to parking rather than the reminder texts.", 100],
  ["evaluate", "medium", "A delivery company says that switching to electric vans will reduce total operating costs over five years.", "Which of the following would be most useful to determine whether the company's prediction is correct?", ["Whether drivers like electric vans more than gas vans.", "Whether charging costs are expected to rise faster than fuel costs.", "Whether the vans are painted white.", "Whether the company uses paper invoices.", "Whether the vans have cup holders."], "B", "Whether charging costs may rise relative to fuel directly bears on whether the main ongoing cost will be lower, which is decisive for the forecast.", 100],
  ["flaw", "medium", "A town found that neighborhoods with more street trees also have lower air pollution. The mayor concludes that planting more trees will necessarily lower pollution in every neighborhood.", "The mayor's reasoning is flawed because it", ["assumes that correlation proves causation.", "uses a survey instead of a census.", "ignores the cost of tree maintenance.", "assumes pollution can never be measured.", "relies on expert testimony."], "A", "The data show an association, not proof that trees caused the lower pollution; the mayor treats correlation as causation.", 100],
  ["inference", "medium", "Every student who submitted the optional practice essay received feedback. Some students who received feedback revised their essays, and every revised essay was submitted before the deadline.", "Which of the following can be inferred from the information above?", ["Every student revised an essay.", "Some students submitted the optional practice essay.", "Some revised essays were submitted before the deadline.", "No student received feedback without revising.", "All students revised the same essay."], "C", "Some students who received feedback revised their essays, and every revised essay was submitted before the deadline, so at least some revised essays were submitted before the deadline.", 100],
  ["paradox", "medium", "A bookstore lowered prices on several slow-selling titles, yet revenue from those titles fell even more sharply.", "Which of the following, if true, best explains the result?", ["The bookstore expanded its coffee menu.", "Customers bought fewer copies than before because the prices were only slightly lower.", "The titles were displayed near the entrance.", "The store changed its logo.", "The books were all hardcovers."], "B", "If the price cut was modest and customers bought fewer copies, revenue can still fall even after prices are lowered.", 100],
  ["boldface", "medium", "The analyst writes that a downtown traffic count dropped after bike lanes were added. **Because traffic counts were taken only during weekday rush hour, the drop may not reflect all traffic conditions.** **Even so, the city should continue expanding bike lanes because the trend is encouraging.**", "In the argument, the first boldfaced statement plays which role, and the second boldfaced statement plays which role?", ["A qualification of the evidence; the conclusion", "The conclusion; a recommendation", "The conclusion; a restatement of the evidence", "A counterclaim; a concession", "A premise; a rebuttal"], "A", "The first boldface limits the significance of the data, so it qualifies the evidence; the second states what the city should do, the argument's conclusion.", 120],
  ["conclusion-main-point", "hard", "A district added later bus routes for students but found that attendance still improved only slightly. The district notes that attendance improved most where buses ran on time and where families were notified the night before. It concludes that schedule reliability and advance notice matter more than route count alone.", "Which of the following best expresses the main point of the argument?", ["More bus routes always improve attendance.", "Attendance never improves without buses.", "Reliability and advance notice matter more than route count alone.", "Families dislike school buses.", "The district should eliminate all late buses."], "C", "The evidence points to two factors, reliability and advance notice, and the conclusion is that these matter more than simply adding routes.", 120],
  ["plan_strategy", "hard", "A nonprofit wants to increase the number of volunteers who return for a second year while keeping training costs low.", "Which of the following is the best strategy for the nonprofit?", ["Offer expensive weekend retreats to all volunteers.", "Reduce training to a single long lecture.", "Assign mentors and provide brief monthly check-ins.", "Replace all in-person coordination with printed mailings.", "Increase annual dues for volunteers."], "C", "Mentors and brief check-ins directly support retention at relatively low cost, fitting the nonprofit's dual goal.", 120],
  ["assumption", "hard", "A software firm says that replacing in-person support with an online knowledge base will lower service costs because most customers can solve problems on their own.", "Which of the following is an assumption required by the argument?", ["The knowledge base will be written in complete sentences.", "Customers will be willing and able to use the knowledge base.", "The firm has more than one product line.", "The firm already has low service costs.", "Support agents prefer working remotely."], "B", "The plan lowers costs only if customers actually use and benefit from the knowledge base, which the argument must assume.", 120],
  ["strengthen", "hard", "A farm says that using drip irrigation will raise crop yields because the soil stays moist more evenly.", "Which of the following, if true, most strengthens the farm's reasoning?", ["The farm grows two kinds of crops.", "Other farms using drip irrigation in the region reported higher yields.", "The farm's workers prefer not to carry hoses.", "The drip system requires more pipes.", "Some crops are harvested in the morning."], "B", "If similar farms saw higher yields after adopting drip irrigation, that supports the claim that the method can improve yields.", 120],
  ["weaken", "hard", "A city says that a new sidewalk repair program improved pedestrian safety because foot injuries on the repaired blocks declined after the work was completed.", "Which of the following, if true, most weakens the city's claim?", ["The repaired blocks are in a shopping district.", "Fewer pedestrians used the repaired blocks after the work was completed.", "The repair crews worked at night.", "The city used the same contractor on every block.", "Some pedestrians also use buses."], "B", "If fewer pedestrians used the repaired blocks, injuries could fall simply because exposure fell, not because the sidewalks became safer.", 120],
  ["evaluate", "hard", "A rail line plans to replace paper tickets with a mobile app and expects the change to cut queue times.", "Which of the following would be most useful to know in evaluating the plan?", ["How many employees prefer paper tickets.", "Whether most riders already carry smartphones with data access.", "Whether the trains are painted blue.", "Whether the app has a logo.", "Whether the station has a café."], "B", "The plan works only if riders can use the app, so whether most riders have smartphones with data access is directly relevant.", 120],
  ["flaw", "hard", "A retailer notes that stores that began offering self-checkout also saw higher customer satisfaction scores. The retailer concludes that self-checkout causes higher satisfaction.", "The retailer's reasoning is most vulnerable to the criticism that it", ["assumes that stores with self-checkout are otherwise identical to stores without it.", "uses numbers instead of words.", "ignores the weather.", "relies on a single store.", "assumes satisfaction cannot be measured."], "A", "Different stores may differ in many ways besides self-checkout; the retailer assumes the groups are otherwise equivalent and treats correlation as causation.", 120],
  ["inference", "hard", "Only applicants who passed the first screening interview were invited to a final interview. Some applicants who were invited to a final interview declined the invitation.", "Which of the following can be inferred from the information above?", ["Every applicant passed the first screening interview.", "Some applicants passed the first screening interview.", "All applicants accepted the final interview.", "No applicant declined the invitation.", "The final interview was more difficult than the first screening."], "B", "Since only those who passed the first screening were invited, and some applicants were invited (some of whom declined), at least some applicants passed the first screening.", 120],
  ["paradox", "hard", "A city's bike-share system added many stations, yet average daily rides per station fell.", "Which of the following, if true, best explains the result?", ["The new stations were placed in areas with little existing demand.", "The city had a mild winter.", "More people owned bikes than before.", "The bikes were changed to a different color.", "Some stations were near parks."], "A", "If the new stations were added where demand was low, total rides are spread across more stations, lowering the average rides per station.", 120],
  ["boldface", "hard", "The report notes that a city pilot program for shaded bus stops reduced complaints about heat, although the number of complaints was already falling before the pilot began. **The pilot only covered stops on the downtown route.** **City officials should expand the shaded-stop program to all major routes.**", "In the argument, the first boldfaced statement plays which role, and the second boldfaced statement plays which role?", ["A limitation on the evidence; a recommendation", "A conclusion; a premise", "A counterexample; a conclusion", "A premise; a recommendation", "A conclusion; a recommendation"], "A", "The first boldface limits how broadly the pilot results apply, so it is a limitation on the evidence; the second is a recommendation to expand the program.", 150],
  ["conclusion-main-point", "hard", "A county found that residents who used the new online permit system submitted forms more accurately, but only after the county added live chat support. The county concludes that technology works best when paired with human assistance.", "Which of the following best expresses the main point of the argument?", ["Online permit systems should replace all county offices.", "Technology works best when paired with human assistance.", "Live chat support is always required.", "Residents dislike online forms.", "The county should abandon technology."], "B", "The evidence supports the broader claim that technology is most effective when paired with human help, which is the conclusion.", 150],
  ["plan_strategy", "hard", "A public library wants to increase teen visits without reducing quiet space for other patrons.", "Which of the following plans best meets the library's goal?", ["Replace all reading tables with gaming stations.", "Hold teen events in a separate room after school hours.", "Ban all teens from the library.", "Reduce the number of books in the collection.", "Close the library on weekdays."], "B", "A separate room after school can attract teens while preserving the quiet area, meeting the goal and its constraint.", 150],
  ["assumption", "easy", "A coffee shop claims that adding mobile ordering will increase morning sales because customers who are in a hurry will buy more drinks if they can order ahead.", "Which of the following is an assumption on which the claim depends?", ["The shop already has a large patio.", "Hurrying customers will actually use mobile ordering.", "The shop sells pastries.", "Coffee beans are dark roasted.", "The shop's logo is unchanged."], "B", "The claim works only if hurried customers actually use the new ordering option; otherwise the predicted increase would not follow.", 90],
  ["strengthen", "easy", "A commuter rail line says that adding bikes on trains will increase ridership because it makes the service more useful for last-mile travel.", "Which of the following, if true, most strengthens the rail line's argument?", ["Few riders use the trains on rainy days.", "Many potential riders currently avoid the line because they need a bike at the destination.", "The trains are painted in the company's colors.", "The line uses ticket scanners.", "The stations are near office buildings."], "B", "If many potential riders avoid the line because they need a bike at their destination, adding bikes directly addresses that barrier.", 90],
  ["weaken", "easy", "A farm claims that a new fertilizer increased tomato yield because the harvest was larger after the fertilizer was introduced.", "Which of the following, if true, most weakens the farm's claim?", ["The farm also switched to a better irrigation schedule at the same time.", "The tomatoes were sold at a roadside stand.", "The fertilizer was stored in a blue shed.", "The farm has been open for many years.", "The tomatoes were picked by hand."], "A", "If irrigation also changed at the same time, the larger harvest may be due to watering rather than the fertilizer.", 90],
  ["evaluate", "easy", "A city plans to add public water fountains in parks and expects fewer plastic bottles to be sold there.", "Which of the following would be most useful to know in evaluating the plan?", ["Whether the parks have benches.", "Whether visitors already bring reusable bottles.", "Whether the city has a mascot.", "Whether the fountains are painted green.", "Whether the parks host concerts."], "B", "If visitors already bring reusable bottles, the new fountains may have little effect on bottle sales, which is directly useful in evaluating the plan.", 90],
  ["flaw", "easy", "An office found that employees who sit near windows take fewer sick days. The manager concludes that moving everyone near windows will reduce sick leave.", "The manager's reasoning is flawed because it", ["assumes that proximity to windows causes fewer sick days.", "uses too many statistics.", "ignores the weather.", "assumes sick days are never planned.", "compares only two departments."], "A", "The manager infers a cause from an observed association; other factors could explain why window seats correlate with fewer sick days.", 90],
  ["inference", "easy", "The train was delayed by weather, so the company offered refunds to passengers on the affected route. Passengers on other routes received no refunds.", "Which of the following can be inferred from the information above?", ["All passengers received refunds.", "Some passengers on the affected route received refunds.", "Weather never affects trains.", "Other routes were also delayed.", "Refunds were given before the delay."], "B", "Refunds were offered to passengers on the affected route, so at least some passengers on that route received them.", 90],
  ["paradox", "easy", "A small airline sold more tickets this month than last month, yet it flew fewer passengers.", "Which of the following, if true, best explains the apparent discrepancy?", ["More tickets were sold for future flights.", "The airline changed its website font.", "The airline served more snack options.", "The airline added more seats.", "Passengers liked the pilots."], "A", "If many tickets were sold for future flights, ticket sales can rise while the number of passengers flown this month falls.", 90],
  ["boldface", "easy", "The memo argues that the city's shared scooter program should be expanded because it reduced short car trips in the pilot area. **The pilot covered only neighborhoods with existing bike lanes.** **Therefore, the city should study whether the effect extends to other neighborhoods before expanding the program.**", "In the argument, the first boldfaced statement plays which role, and the second boldfaced statement plays which role?", ["A limitation on the evidence; a recommendation", "A conclusion; a premise", "A counterexample; a conclusion", "A premise; a recommendation", "A conclusion; a recommendation"], "A", "The first boldface narrows the pilot's scope, limiting the evidence; the second recommends studying whether the result generalizes.", 100],
  ["conclusion-main-point", "medium", "A city added more trash bins to a park and later found less litter near the bins but more litter at the park's edges. Officials conclude that adding bins can shift litter unless cleanup covers the whole park.", "Which of the following best states the main point of the argument?", ["Trash bins never reduce litter.", "Adding bins can shift litter unless cleanup is broader.", "The park should remove all bins.", "Litter is caused by trash bins.", "Edges of parks are always dirty."], "B", "The conclusion is not just that bins matter, but that their benefit can be offset unless cleanup covers the whole park.", 100],
  ["plan_strategy", "medium", "A transit agency wants to reduce late buses without adding many new vehicles.", "Which of the following is the best strategy?", ["Increase the number of routes immediately.", "Reassign some buses to the busiest routes and adjust schedules using real-time data.", "Remove all express routes.", "Close the transit system on rainy days.", "Add more advertising posters."], "B", "Reassigning buses and using real-time data can improve punctuality without needing many new vehicles, fitting the goal.", 100],
  ["assumption", "medium", "A grocery chain says that moving a store's bakery closer to the entrance will increase bakery sales because more shoppers will notice it.", "Which of the following is an assumption required by the argument?", ["The store will stop selling fruit.", "Shoppers do not already notice the bakery well enough from its current location.", "The bakery uses imported flour.", "The store has at least one checkout lane.", "The bakery closes at the same time every day."], "B", "If shoppers already notice the bakery well enough, moving it would not necessarily increase sales; the conclusion depends on current visibility being insufficient.", 100],
  ["strengthen", "medium", "A factory says that its new training videos lowered defect rates because workers made fewer assembly mistakes after watching them.", "Which of the following, if true, most strengthens the factory's argument?", ["The videos were translated into two languages.", "Workers who did not watch the videos did not show a similar drop in mistakes.", "The factory has a large parking lot.", "The videos were shorter than the old manual.", "The factory sells products overseas."], "B", "A comparison group that did not watch the videos and did not improve supports the claim that the videos caused the drop in mistakes.", 100],
  ["weaken", "medium", "A town says that its new art festival increased downtown sales because retailers reported higher revenue during the festival week.", "Which of the following, if true, most weakens the town's claim?", ["The festival included live music.", "Retailers offered large holiday discounts during the same week.", "Some visitors came from neighboring towns.", "The downtown area is walkable.", "The festival had a printed map."], "B", "If retailers also offered large discounts, the higher sales could be due to the discounts rather than the festival.", 100],
  ["evaluate", "medium", "A neighborhood group wants to know whether planting more streetlights will reduce evening thefts.", "Which of the following would be most useful to know in evaluating the proposal?", ["Whether residents prefer warm-colored lights.", "Whether thefts also fell in comparable neighborhoods without more streetlights.", "Whether the poles are made of steel.", "Whether the streetlights are tall.", "Whether the neighborhood has a park."], "B", "A comparable-neighborhood comparison helps determine whether thefts fell because of the lights or because of a broader trend.", 100],
  ["flaw", "medium", "A gym found that members who attend group classes cancel their memberships less often. The gym concludes that group classes prevent cancellations.", "The gym's reasoning is flawed because it", ["assumes that people who attend classes are the same as people who do not in every relevant respect.", "fails to use enough examples.", "ignores the gym's music playlist.", "assumes cancellations are impossible.", "treats a probability as a certainty."], "A", "Members who choose group classes may differ in ways that already make them less likely to cancel; the gym wrongly assumes the association proves causation.", 100],
  ["inference", "medium", "All of the company's interns work part time. Some part-time workers work remotely. No remote worker is a contractor.", "Which of the following can be inferred from the statements above?", ["Some interns work remotely.", "Some part-time workers are not contractors.", "All contractors are interns.", "No intern works remotely.", "Every part-time worker is an intern."], "B", "Some part-time workers work remotely, and no remote worker is a contractor, so some part-time workers are not contractors.", 100],
  ["paradox", "medium", "A clothing store increased the number of sale signs, yet fewer items were sold at full price and total profit rose.", "Which of the following, if true, best explains the result?", ["The sale signs were printed in large font.", "The store's most expensive items were excluded from the sale.", "Customers shopped earlier in the day.", "The store changed its music.", "The store added more mirrors."], "B", "If the most expensive items were excluded from the sale, the store could sell fewer full-price items yet earn more profit by clearing lower-margin items while keeping high-margin items at full price.", 100],
  ["boldface", "medium", "The analyst notes that the city's bike-share usage rose after the city expanded the network. **The city expanded the network only in neighborhoods that already had high ridership.** **So the expansion was probably not the only reason usage rose.**", "In the argument, the first boldfaced statement plays which role, and the second boldfaced statement plays which role?", ["A qualification of the evidence; a conclusion", "A premise; a conclusion", "A conclusion; a premise", "A counterexample; a premise", "A recommendation; a conclusion"], "A", "The first boldface limits the scope of the evidence, suggesting preexisting ridership; the second states the argument's conclusion about causation.", 120],
  ["conclusion-main-point", "hard", "A university found that students who used its peer-writing center more than twice received stronger final papers, but only when they also attended at least one instructor conference. The university concludes that combining peer and instructor feedback is more effective than either source alone.", "Which of the following best states the main point of the argument?", ["Peer-writing centers should replace instructor conferences.", "Students who attend conferences always write better papers.", "Combining peer and instructor feedback is more effective than either alone.", "All students should visit the writing center exactly twice.", "Instructor conferences are unnecessary."], "C", "The conclusion is that the combination of peer and instructor feedback is more effective than either alone.", 150],
  ["plan_strategy", "hard", "A museum wants to increase visits from families with children while keeping admission prices unchanged.", "Which of the following is the best strategy?", ["Raise admission prices and offer fewer programs.", "Create family-themed weekends with hands-on exhibits using the current staff.", "Reduce the museum's hours by half.", "Stop advertising to families.", "Convert the museum into office space."], "B", "Family weekends and hands-on exhibits are likely to attract families without changing admission prices or requiring a major new expense.", 150],
];

// ── Data Sufficiency (10) — g3-ds-91..100 ─────────────────────────────────────
const DS = [
  ["arithmetic", "easy", "What is the value of $x$?\n\n(1) $x+5=12$\n(2) $x-3=4$", "D", "From (1), $x=7$. From (2), $x=7$. Each statement alone is sufficient.", 120],
  ["geometry", "medium", "Is the area of the circle greater than $200$?\n\n(1) The radius is $7$.\n(2) The circumference is $44$.", "D", "From (1), area $=49\\pi\\approx 154<200$, so the answer is no. From (2), $2\\pi r=44$ gives $r\\approx 7$, so area $\\approx 154<200$, again no. Each statement alone is sufficient.", 120],
  ["statistics", "medium", "What is the mean of a set of scores?\n\n(1) The scores total $280$.\n(2) There are four scores, three of which are $60$, $70$, and $80$.", "C", "From (1) alone the number of scores is unknown. From (2) alone the total is unknown. Together, there are four scores totaling $280$, so the fourth is $280-210=70$ and the mean is $280/4=70$.", 120],
  ["rates_work", "medium", "How long would Machine A take to finish the job alone?\n\n(1) Machines A and B together finish the job in $6$ hours.\n(2) Machine B alone finishes the job in $10$ hours.", "C", "Neither statement alone fixes A's rate. Together, the combined rate is $\\frac{1}{6}$ and B's rate is $\\frac{1}{10}$, so A's rate is $\\frac{1}{6}-\\frac{1}{10}=\\frac{1}{15}$, and A alone takes $15$ hours.", 120],
  ["overlapping_sets", "medium", "How many students are in neither club?\n\n(1) $20$ students are in Art Club, $18$ are in Music Club, and $8$ are in both.\n(2) The grade has $35$ students.", "C", "From (1), the union is $20+18-8=30$. From (2), the total is $35$. Together, the number in neither club is $35-30=5$.", 120],
  ["number_properties", "hard", "Is $n$ divisible by $24$?\n\n(1) $n$ is divisible by $6$ and by $8$.\n(2) $n$ is divisible by $12$ and by $2$.", "A", "From (1), being divisible by both $6$ and $8$ means being divisible by their least common multiple, $24$ — sufficient. From (2), divisibility by $12$ and $2$ only requires divisibility by $12$ (for example $12$ itself), so it is not sufficient.", 120],
  ["geometry", "medium", "In triangle $ABC$, what is the measure of $\\angle A$?\n\n(1) $AB=AC$ and $\\angle B=36^\\circ$.\n(2) $\\angle C=72^\\circ$.", "A", "From (1), $AB=AC$ makes the base angles equal, so $\\angle C=\\angle B=36^\\circ$ and $\\angle A=180-36-36=108^\\circ$ — sufficient. From (2) alone, $\\angle A$ is not determined.", 120],
  ["algebra", "hard", "What is the value of $x$?\n\n(1) $x^2-5x=0$\n(2) $x-5=0$", "B", "From (1), $x=0$ or $x=5$ — not sufficient. From (2), $x=5$ — sufficient.", 120],
  ["statistics", "hard", "What is the median of the data set?\n\n(1) The mean is $18$.\n(2) The range is $12$.", "E", "Knowing only the mean or only the range does not determine the median, and even together many data sets with mean $18$ and range $12$ have different medians.", 120],
  ["word_problems", "hard", "How many miles can a car travel on $g$ gallons of fuel?\n\n(1) The car gets $30$ miles per gallon in the city and $40$ miles per gallon on the highway.\n(2) The trip uses only highway driving.", "C", "From (1) alone the driving mix is unknown. From (2) alone the fuel-efficiency rate is unknown. Together, the highway rate applies, so the car travels $40g$ miles.", 120],
];

// ── Assemble + write ──────────────────────────────────────────────────────────
const quant = PS.map((row, i) => ps(`g3-quant-${String(i + 1).padStart(2, "0")}`, row));
const verbal = CR.map((row, i) => cr(`g3-cr-${i + 41}`, row));
const dataInsights = DS.map((row, i) => ds(`g3-ds-${i + 91}`, row));

const out = (rel, data) => {
  writeFileSync(resolve(root, rel), JSON.stringify(data, null, 2) + "\n");
  console.log(`  wrote ${rel} (${data.length} items)`);
};

out("content/questions/quant-11.json", quant);
out("content/questions/verbal-11.json", verbal);
out("content/questions/data_insights-11.json", dataInsights);

console.log(`\nbatch11: ${quant.length} PS + ${verbal.length} CR + ${dataInsights.length} DS = ${quant.length + verbal.length + dataInsights.length} questions`);
